// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PSimpleBean.proto

package org.redkalex.test.protobuf;

public final class PSimpleBeanOuterClass {
  private PSimpleBeanOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PSimpleBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PSimpleBean)
      com.google.protobuf.MessageOrBuilder { 

    /**
     * <code>.PSimpleBean.PSimpleEntry simple = 1;</code>
     * @return Whether the simple field is set.
     */
    boolean hasSimple();
    /**
     * <code>.PSimpleBean.PSimpleEntry simple = 1;</code>
     * @return The simple.
     */
    org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry getSimple();
    /**
     * <code>.PSimpleBean.PSimpleEntry simple = 1;</code>
     */
    org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntryOrBuilder getSimpleOrBuilder();

    /**
     * <code>.PSimpleBean.PTwoEntry two = 2;</code>
     * @return Whether the two field is set.
     */
    boolean hasTwo();
    /**
     * <code>.PSimpleBean.PTwoEntry two = 2;</code>
     * @return The two.
     */
    org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry getTwo();
    /**
     * <code>.PSimpleBean.PTwoEntry two = 2;</code>
     */
    org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntryOrBuilder getTwoOrBuilder();

    /**
     * <code>string strings = 3;</code>
     * @return The strings.
     */
    java.lang.String getStrings();
    /**
     * <code>string strings = 3;</code>
     * @return The bytes for strings.
     */
    com.google.protobuf.ByteString
        getStringsBytes();
  }
  /**
   * Protobuf type {@code PSimpleBean}
   */
  public static final class PSimpleBean extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PSimpleBean)
      PSimpleBeanOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PSimpleBean.newBuilder() to construct.
    private PSimpleBean(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PSimpleBean() {
      strings_ = "";
    }


    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PSimpleBean();
    }

    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PSimpleBean(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry.Builder subBuilder = null;
              if (simple_ != null) {
                subBuilder = simple_.toBuilder();
              }
              simple_ = input.readMessage(org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(simple_);
                simple_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry.Builder subBuilder = null;
              if (two_ != null) {
                subBuilder = two_.toBuilder();
              }
              two_ = input.readMessage(org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(two_);
                two_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              strings_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.redkalex.test.protobuf.PSimpleBeanOuterClass.internal_static_PSimpleBean_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.redkalex.test.protobuf.PSimpleBeanOuterClass.internal_static_PSimpleBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.class, org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.Builder.class);
    }

    public interface PSimpleEntryOrBuilder extends
        // @@protoc_insertion_point(interface_extends:PSimpleBean.PSimpleEntry)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>sint32 id = 1;</code>
       * @return The id.
       */
      int getId();

      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      java.lang.String getName();
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>string email = 3;</code>
       * @return The email.
       */
      java.lang.String getEmail();
      /**
       * <code>string email = 3;</code>
       * @return The bytes for email.
       */
      com.google.protobuf.ByteString
          getEmailBytes();
    }
    /**
     * Protobuf type {@code PSimpleBean.PSimpleEntry}
     */
    public static final class PSimpleEntry extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:PSimpleBean.PSimpleEntry)
        PSimpleEntryOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use PSimpleEntry.newBuilder() to construct.
      private PSimpleEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private PSimpleEntry() {
        name_ = "";
        email_ = "";
      }


      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new PSimpleEntry();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private PSimpleEntry(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                id_ = input.readSInt32();
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();

                email_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.redkalex.test.protobuf.PSimpleBeanOuterClass.internal_static_PSimpleBean_PSimpleEntry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.redkalex.test.protobuf.PSimpleBeanOuterClass.internal_static_PSimpleBean_PSimpleEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry.class, org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry.Builder.class);
      }

      public static final int ID_FIELD_NUMBER = 1;
      private int id_;
      /**
       * <code>sint32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }

      public static final int NAME_FIELD_NUMBER = 2;
      private volatile java.lang.Object name_;
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      @java.lang.Override
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int EMAIL_FIELD_NUMBER = 3;
      private volatile java.lang.Object email_;
      /**
       * <code>string email = 3;</code>
       * @return The email.
       */
      @java.lang.Override
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @return The bytes for email.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (id_ != 0) {
          output.writeSInt32(1, id_);
        }
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
        }
        if (!getEmailBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (id_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeSInt32Size(1, id_);
        }
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
        }
        if (!getEmailBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry)) {
          return super.equals(obj);
        }
        org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry other = (org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry) obj;

        if (getId()
            != other.getId()) return false;
        if (!getName()
            .equals(other.getName())) return false;
        if (!getEmail()
            .equals(other.getEmail())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + EMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getEmail().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code PSimpleBean.PSimpleEntry}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:PSimpleBean.PSimpleEntry)
          org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntryOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.redkalex.test.protobuf.PSimpleBeanOuterClass.internal_static_PSimpleBean_PSimpleEntry_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.redkalex.test.protobuf.PSimpleBeanOuterClass.internal_static_PSimpleBean_PSimpleEntry_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry.class, org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry.Builder.class);
        }

        // Construct using org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          id_ = 0;

          name_ = "";

          email_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.redkalex.test.protobuf.PSimpleBeanOuterClass.internal_static_PSimpleBean_PSimpleEntry_descriptor;
        }

        @java.lang.Override
        public org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry getDefaultInstanceForType() {
          return org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry.getDefaultInstance();
        }

        @java.lang.Override
        public org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry build() {
          org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry buildPartial() {
          org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry result = new org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry(this);
          result.id_ = id_;
          result.name_ = name_;
          result.email_ = email_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry) {
            return mergeFrom((org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry other) {
          if (other == org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry.getDefaultInstance()) return this;
          if (other.getId() != 0) {
            setId(other.getId());
          }
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          if (!other.getEmail().isEmpty()) {
            email_ = other.email_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int id_ ;
        /**
         * <code>sint32 id = 1;</code>
         * @return The id.
         */
        @java.lang.Override
        public int getId() {
          return id_;
        }
        /**
         * <code>sint32 id = 1;</code>
         * @param value The id to set.
         * @return This builder for chaining.
         */
        public Builder setId(int value) {
          
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>sint32 id = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearId() {
          
          id_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>string name = 2;</code>
         * @return The name.
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string name = 2;</code>
         * @return The bytes for name.
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 2;</code>
         * @param value The name to set.
         * @return This builder for chaining.
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>string name = 2;</code>
         * @param value The bytes for name to set.
         * @return This builder for chaining.
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object email_ = "";
        /**
         * <code>string email = 3;</code>
         * @return The email.
         */
        public java.lang.String getEmail() {
          java.lang.Object ref = email_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            email_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string email = 3;</code>
         * @return The bytes for email.
         */
        public com.google.protobuf.ByteString
            getEmailBytes() {
          java.lang.Object ref = email_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            email_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string email = 3;</code>
         * @param value The email to set.
         * @return This builder for chaining.
         */
        public Builder setEmail(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          email_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string email = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearEmail() {
          
          email_ = getDefaultInstance().getEmail();
          onChanged();
          return this;
        }
        /**
         * <code>string email = 3;</code>
         * @param value The bytes for email to set.
         * @return This builder for chaining.
         */
        public Builder setEmailBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          email_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:PSimpleBean.PSimpleEntry)
      }

      // @@protoc_insertion_point(class_scope:PSimpleBean.PSimpleEntry)
      private static final org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry();
      }

      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<PSimpleEntry>
          PARSER = new com.google.protobuf.AbstractParser<PSimpleEntry>() {
        @java.lang.Override
        public PSimpleEntry parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new PSimpleEntry(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<PSimpleEntry> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<PSimpleEntry> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface PTwoEntryOrBuilder extends
        // @@protoc_insertion_point(interface_extends:PSimpleBean.PTwoEntry)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>sint32 status = 1;</code>
       * @return The status.
       */
      int getStatus();

      /**
       * <code>sint64 createtime = 2;</code>
       * @return The createtime.
       */
      long getCreatetime();
    }
    /**
     * Protobuf type {@code PSimpleBean.PTwoEntry}
     */
    public static final class PTwoEntry extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:PSimpleBean.PTwoEntry)
        PTwoEntryOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use PTwoEntry.newBuilder() to construct.
      private PTwoEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private PTwoEntry() {
      }


      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) { 
        return new PTwoEntry();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private PTwoEntry(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                status_ = input.readSInt32();
                break;
              }
              case 16: {

                createtime_ = input.readSInt64();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.redkalex.test.protobuf.PSimpleBeanOuterClass.internal_static_PSimpleBean_PTwoEntry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.redkalex.test.protobuf.PSimpleBeanOuterClass.internal_static_PSimpleBean_PTwoEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry.class, org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry.Builder.class);
      }

      public static final int STATUS_FIELD_NUMBER = 1;
      private int status_;
      /**
       * <code>sint32 status = 1;</code>
       * @return The status.
       */
      @java.lang.Override
      public int getStatus() {
        return status_;
      }

      public static final int CREATETIME_FIELD_NUMBER = 2;
      private long createtime_;
      /**
       * <code>sint64 createtime = 2;</code>
       * @return The createtime.
       */
      @java.lang.Override
      public long getCreatetime() {
        return createtime_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (status_ != 0) {
          output.writeSInt32(1, status_);
        }
        if (createtime_ != 0L) {
          output.writeSInt64(2, createtime_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (status_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeSInt32Size(1, status_);
        }
        if (createtime_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeSInt64Size(2, createtime_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry)) {
          return super.equals(obj);
        }
        org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry other = (org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry) obj;

        if (getStatus()
            != other.getStatus()) return false;
        if (getCreatetime()
            != other.getCreatetime()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus();
        hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCreatetime());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code PSimpleBean.PTwoEntry}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:PSimpleBean.PTwoEntry)
          org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntryOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.redkalex.test.protobuf.PSimpleBeanOuterClass.internal_static_PSimpleBean_PTwoEntry_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.redkalex.test.protobuf.PSimpleBeanOuterClass.internal_static_PSimpleBean_PTwoEntry_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry.class, org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry.Builder.class);
        }

        // Construct using org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          status_ = 0;

          createtime_ = 0L;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.redkalex.test.protobuf.PSimpleBeanOuterClass.internal_static_PSimpleBean_PTwoEntry_descriptor;
        }

        @java.lang.Override
        public org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry getDefaultInstanceForType() {
          return org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry.getDefaultInstance();
        }

        @java.lang.Override
        public org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry build() {
          org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry buildPartial() {
          org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry result = new org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry(this);
          result.status_ = status_;
          result.createtime_ = createtime_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry) {
            return mergeFrom((org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry other) {
          if (other == org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry.getDefaultInstance()) return this;
          if (other.getStatus() != 0) {
            setStatus(other.getStatus());
          }
          if (other.getCreatetime() != 0L) {
            setCreatetime(other.getCreatetime());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int status_ ;
        /**
         * <code>sint32 status = 1;</code>
         * @return The status.
         */
        @java.lang.Override
        public int getStatus() {
          return status_;
        }
        /**
         * <code>sint32 status = 1;</code>
         * @param value The status to set.
         * @return This builder for chaining.
         */
        public Builder setStatus(int value) {
          
          status_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>sint32 status = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearStatus() {
          
          status_ = 0;
          onChanged();
          return this;
        }

        private long createtime_ ;
        /**
         * <code>sint64 createtime = 2;</code>
         * @return The createtime.
         */
        @java.lang.Override
        public long getCreatetime() {
          return createtime_;
        }
        /**
         * <code>sint64 createtime = 2;</code>
         * @param value The createtime to set.
         * @return This builder for chaining.
         */
        public Builder setCreatetime(long value) {
          
          createtime_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>sint64 createtime = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearCreatetime() {
          
          createtime_ = 0L;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:PSimpleBean.PTwoEntry)
      }

      // @@protoc_insertion_point(class_scope:PSimpleBean.PTwoEntry)
      private static final org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry();
      }

      public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<PTwoEntry>
          PARSER = new com.google.protobuf.AbstractParser<PTwoEntry>() {
        @java.lang.Override
        public PTwoEntry parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new PTwoEntry(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<PTwoEntry> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<PTwoEntry> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int SIMPLE_FIELD_NUMBER = 1;
    private org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry simple_;
    /**
     * <code>.PSimpleBean.PSimpleEntry simple = 1;</code>
     * @return Whether the simple field is set.
     */
    @java.lang.Override
    public boolean hasSimple() {
      return simple_ != null;
    }
    /**
     * <code>.PSimpleBean.PSimpleEntry simple = 1;</code>
     * @return The simple.
     */
    @java.lang.Override
    public org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry getSimple() {
      return simple_ == null ? org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry.getDefaultInstance() : simple_;
    }
    /**
     * <code>.PSimpleBean.PSimpleEntry simple = 1;</code>
     */
    @java.lang.Override
    public org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntryOrBuilder getSimpleOrBuilder() {
      return getSimple();
    }

    public static final int TWO_FIELD_NUMBER = 2;
    private org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry two_;
    /**
     * <code>.PSimpleBean.PTwoEntry two = 2;</code>
     * @return Whether the two field is set.
     */
    @java.lang.Override
    public boolean hasTwo() {
      return two_ != null;
    }
    /**
     * <code>.PSimpleBean.PTwoEntry two = 2;</code>
     * @return The two.
     */
    @java.lang.Override
    public org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry getTwo() {
      return two_ == null ? org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry.getDefaultInstance() : two_;
    }
    /**
     * <code>.PSimpleBean.PTwoEntry two = 2;</code>
     */
    @java.lang.Override
    public org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntryOrBuilder getTwoOrBuilder() {
      return getTwo();
    }

    public static final int STRINGS_FIELD_NUMBER = 3;
    private volatile java.lang.Object strings_;
    /**
     * <code>string strings = 3;</code>
     * @return The strings.
     */
    @java.lang.Override
    public java.lang.String getStrings() {
      java.lang.Object ref = strings_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        strings_ = s;
        return s;
      }
    }
    /**
     * <code>string strings = 3;</code>
     * @return The bytes for strings.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStringsBytes() {
      java.lang.Object ref = strings_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strings_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (simple_ != null) {
        output.writeMessage(1, getSimple());
      }
      if (two_ != null) {
        output.writeMessage(2, getTwo());
      }
      if (!getStringsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, strings_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (simple_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSimple());
      }
      if (two_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTwo());
      }
      if (!getStringsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, strings_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean)) {
        return super.equals(obj);
      }
      org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean other = (org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean) obj;

      if (hasSimple() != other.hasSimple()) return false;
      if (hasSimple()) {
        if (!getSimple()
            .equals(other.getSimple())) return false;
      }
      if (hasTwo() != other.hasTwo()) return false;
      if (hasTwo()) {
        if (!getTwo()
            .equals(other.getTwo())) return false;
      }
      if (!getStrings()
          .equals(other.getStrings())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSimple()) {
        hash = (37 * hash) + SIMPLE_FIELD_NUMBER;
        hash = (53 * hash) + getSimple().hashCode();
      }
      if (hasTwo()) {
        hash = (37 * hash) + TWO_FIELD_NUMBER;
        hash = (53 * hash) + getTwo().hashCode();
      }
      hash = (37 * hash) + STRINGS_FIELD_NUMBER;
      hash = (53 * hash) + getStrings().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PSimpleBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PSimpleBean)
        org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.redkalex.test.protobuf.PSimpleBeanOuterClass.internal_static_PSimpleBean_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.redkalex.test.protobuf.PSimpleBeanOuterClass.internal_static_PSimpleBean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.class, org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.Builder.class);
      }

      // Construct using org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (simpleBuilder_ == null) {
          simple_ = null;
        } else {
          simple_ = null;
          simpleBuilder_ = null;
        }
        if (twoBuilder_ == null) {
          two_ = null;
        } else {
          two_ = null;
          twoBuilder_ = null;
        }
        strings_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.redkalex.test.protobuf.PSimpleBeanOuterClass.internal_static_PSimpleBean_descriptor;
      }

      @java.lang.Override
      public org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean getDefaultInstanceForType() {
        return org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.getDefaultInstance();
      }

      @java.lang.Override
      public org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean build() {
        org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean buildPartial() {
        org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean result = new org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean(this);
        if (simpleBuilder_ == null) {
          result.simple_ = simple_;
        } else {
          result.simple_ = simpleBuilder_.build();
        }
        if (twoBuilder_ == null) {
          result.two_ = two_;
        } else {
          result.two_ = twoBuilder_.build();
        }
        result.strings_ = strings_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean) {
          return mergeFrom((org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean other) {
        if (other == org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.getDefaultInstance()) return this;
        if (other.hasSimple()) {
          mergeSimple(other.getSimple());
        }
        if (other.hasTwo()) {
          mergeTwo(other.getTwo());
        }
        if (!other.getStrings().isEmpty()) {
          strings_ = other.strings_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry simple_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry, org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry.Builder, org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntryOrBuilder> simpleBuilder_;
      /**
       * <code>.PSimpleBean.PSimpleEntry simple = 1;</code>
       * @return Whether the simple field is set.
       */
      public boolean hasSimple() {
        return simpleBuilder_ != null || simple_ != null;
      }
      /**
       * <code>.PSimpleBean.PSimpleEntry simple = 1;</code>
       * @return The simple.
       */
      public org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry getSimple() {
        if (simpleBuilder_ == null) {
          return simple_ == null ? org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry.getDefaultInstance() : simple_;
        } else {
          return simpleBuilder_.getMessage();
        }
      }
      /**
       * <code>.PSimpleBean.PSimpleEntry simple = 1;</code>
       */
      public Builder setSimple(org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry value) {
        if (simpleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          simple_ = value;
          onChanged();
        } else {
          simpleBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.PSimpleBean.PSimpleEntry simple = 1;</code>
       */
      public Builder setSimple(
          org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry.Builder builderForValue) {
        if (simpleBuilder_ == null) {
          simple_ = builderForValue.build();
          onChanged();
        } else {
          simpleBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.PSimpleBean.PSimpleEntry simple = 1;</code>
       */
      public Builder mergeSimple(org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry value) {
        if (simpleBuilder_ == null) {
          if (simple_ != null) {
            simple_ =
              org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry.newBuilder(simple_).mergeFrom(value).buildPartial();
          } else {
            simple_ = value;
          }
          onChanged();
        } else {
          simpleBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.PSimpleBean.PSimpleEntry simple = 1;</code>
       */
      public Builder clearSimple() {
        if (simpleBuilder_ == null) {
          simple_ = null;
          onChanged();
        } else {
          simple_ = null;
          simpleBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.PSimpleBean.PSimpleEntry simple = 1;</code>
       */
      public org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry.Builder getSimpleBuilder() {
        
        onChanged();
        return getSimpleFieldBuilder().getBuilder();
      }
      /**
       * <code>.PSimpleBean.PSimpleEntry simple = 1;</code>
       */
      public org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntryOrBuilder getSimpleOrBuilder() {
        if (simpleBuilder_ != null) {
          return simpleBuilder_.getMessageOrBuilder();
        } else {
          return simple_ == null ?
              org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry.getDefaultInstance() : simple_;
        }
      }
      /**
       * <code>.PSimpleBean.PSimpleEntry simple = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry, org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry.Builder, org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntryOrBuilder> 
          getSimpleFieldBuilder() {
        if (simpleBuilder_ == null) {
          simpleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry, org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntry.Builder, org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PSimpleEntryOrBuilder>(
                  getSimple(),
                  getParentForChildren(),
                  isClean());
          simple_ = null;
        }
        return simpleBuilder_;
      }

      private org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry two_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry, org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry.Builder, org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntryOrBuilder> twoBuilder_;
      /**
       * <code>.PSimpleBean.PTwoEntry two = 2;</code>
       * @return Whether the two field is set.
       */
      public boolean hasTwo() {
        return twoBuilder_ != null || two_ != null;
      }
      /**
       * <code>.PSimpleBean.PTwoEntry two = 2;</code>
       * @return The two.
       */
      public org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry getTwo() {
        if (twoBuilder_ == null) {
          return two_ == null ? org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry.getDefaultInstance() : two_;
        } else {
          return twoBuilder_.getMessage();
        }
      }
      /**
       * <code>.PSimpleBean.PTwoEntry two = 2;</code>
       */
      public Builder setTwo(org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry value) {
        if (twoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          two_ = value;
          onChanged();
        } else {
          twoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.PSimpleBean.PTwoEntry two = 2;</code>
       */
      public Builder setTwo(
          org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry.Builder builderForValue) {
        if (twoBuilder_ == null) {
          two_ = builderForValue.build();
          onChanged();
        } else {
          twoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.PSimpleBean.PTwoEntry two = 2;</code>
       */
      public Builder mergeTwo(org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry value) {
        if (twoBuilder_ == null) {
          if (two_ != null) {
            two_ =
              org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry.newBuilder(two_).mergeFrom(value).buildPartial();
          } else {
            two_ = value;
          }
          onChanged();
        } else {
          twoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.PSimpleBean.PTwoEntry two = 2;</code>
       */
      public Builder clearTwo() {
        if (twoBuilder_ == null) {
          two_ = null;
          onChanged();
        } else {
          two_ = null;
          twoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.PSimpleBean.PTwoEntry two = 2;</code>
       */
      public org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry.Builder getTwoBuilder() {
        
        onChanged();
        return getTwoFieldBuilder().getBuilder();
      }
      /**
       * <code>.PSimpleBean.PTwoEntry two = 2;</code>
       */
      public org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntryOrBuilder getTwoOrBuilder() {
        if (twoBuilder_ != null) {
          return twoBuilder_.getMessageOrBuilder();
        } else {
          return two_ == null ?
              org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry.getDefaultInstance() : two_;
        }
      }
      /**
       * <code>.PSimpleBean.PTwoEntry two = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry, org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry.Builder, org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntryOrBuilder> 
          getTwoFieldBuilder() {
        if (twoBuilder_ == null) {
          twoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry, org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntry.Builder, org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean.PTwoEntryOrBuilder>(
                  getTwo(),
                  getParentForChildren(),
                  isClean());
          two_ = null;
        }
        return twoBuilder_;
      }

      private java.lang.Object strings_ = "";
      /**
       * <code>string strings = 3;</code>
       * @return The strings.
       */
      public java.lang.String getStrings() {
        java.lang.Object ref = strings_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          strings_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string strings = 3;</code>
       * @return The bytes for strings.
       */
      public com.google.protobuf.ByteString
          getStringsBytes() {
        java.lang.Object ref = strings_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          strings_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string strings = 3;</code>
       * @param value The strings to set.
       * @return This builder for chaining.
       */
      public Builder setStrings(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        strings_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string strings = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStrings() {
        
        strings_ = getDefaultInstance().getStrings();
        onChanged();
        return this;
      }
      /**
       * <code>string strings = 3;</code>
       * @param value The bytes for strings to set.
       * @return This builder for chaining.
       */
      public Builder setStringsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        strings_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PSimpleBean)
    }

    // @@protoc_insertion_point(class_scope:PSimpleBean)
    private static final org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean();
    }

    public static org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PSimpleBean>
        PARSER = new com.google.protobuf.AbstractParser<PSimpleBean>() {
      @java.lang.Override
      public PSimpleBean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PSimpleBean(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PSimpleBean> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PSimpleBean> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.redkalex.test.protobuf.PSimpleBeanOuterClass.PSimpleBean getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PSimpleBean_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PSimpleBean_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PSimpleBean_PSimpleEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PSimpleBean_PSimpleEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PSimpleBean_PTwoEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PSimpleBean_PTwoEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021PSimpleBean.proto\"\330\001\n\013PSimpleBean\022)\n\006s" +
      "imple\030\001 \001(\0132\031.PSimpleBean.PSimpleEntry\022#" +
      "\n\003two\030\002 \001(\0132\026.PSimpleBean.PTwoEntry\022\017\n\007s" +
      "trings\030\003 \001(\t\0327\n\014PSimpleEntry\022\n\n\002id\030\001 \001(\021" +
      "\022\014\n\004name\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\032/\n\tPTwoEnt" +
      "ry\022\016\n\006status\030\001 \001(\021\022\022\n\ncreatetime\030\002 \001(\022B\034" +
      "\n\032org.redkalex.test.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData, 
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PSimpleBean_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PSimpleBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PSimpleBean_descriptor,
        new java.lang.String[] { "Simple", "Two", "Strings", });
    internal_static_PSimpleBean_PSimpleEntry_descriptor =
      internal_static_PSimpleBean_descriptor.getNestedTypes().get(0);
    internal_static_PSimpleBean_PSimpleEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PSimpleBean_PSimpleEntry_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", });
    internal_static_PSimpleBean_PTwoEntry_descriptor =
      internal_static_PSimpleBean_descriptor.getNestedTypes().get(1);
    internal_static_PSimpleBean_PTwoEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PSimpleBean_PTwoEntry_descriptor,
        new java.lang.String[] { "Status", "Createtime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
